name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Clean previous build
      run: npm run clean

    - name: Compile TypeScript
      run: npm run compile

    - name: Copy source files
      run: npm run copy

    - name: Install Flatpak (Ubuntu only)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y flatpak

    - name: Install Flatpak SDK (Ubuntu only)
      if: runner.os == 'Linux'
      run: |
        flatpak install -y flathub org.electron.electron

    - name: Build Electron app
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-build-${{ matrix.os }}
        path: out/
