name: Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Download Linux artifacts
              uses: actions/download-artifact@v3
              with:
                  name: electron-build-ubuntu-latest
                  path: out/linux

            - name: Download macOS artifacts
              uses: actions/download-artifact@v3
              with:
                  name: electron-build-macos-latest
                  path: out/macos

            - name: Download Windows artifacts
              uses: actions/download-artifact@v3
              with:
                  name: electron-build-windows-latest
                  path: out/windows

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload Linux release assets
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: out/linux/appimage_name.AppImage
                  asset_name: linux_appimage.AppImage
                  asset_content_type: application/octet-stream

            - name: Upload macOS release assets
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: out/macos/app.dmg
                  asset_name: macos_app.dmg
                  asset_content_type: application/x-disk-image

            - name: Upload Windows release assets
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: out/windows/installer.exe
                  asset_name: windows_installer.exe
                  asset_content_type: application/x-msdownload

